name: BUILD REACT APP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  REACT_APP_MY_VAR: ${{ vars.REACT_APP_MY_VAR }}
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm install
          npm run build
        env:
          REACT_APP_MY_SECRET: ${{ secrets.MY_SECRET }}
      - name: DEBUG env
        run: env